# Gemini API Keys, In real these keys either will be stored in the consul or vault for security.
GEMINI_API_KEY = "account-Lb473CN4ul89qojCOdNJ"
GEMINI_API_SECRET = "3kc8E4DCQx7nwznJ3p9RKR2g7Rd8"

# API statuses
STATUS_OK = 200
STATUS_CREATED = 201
STATUS_NO_CONTENT = 204
STATUS_BAD_REQUEST = 400
STATUS_UNAUTHORIZED = 401
STATUS_FORBIDDEN = 403
STATUS_NOT_FOUND = 404
STATUS_METHOD_NOT_ALLOWED = 405
STATUS_CONFLICT = 409
STATUS_INTERNAL_SERVER_ERROR = 500
STATUS_BAD_GATEWAY = 502
STATUS_SERVICE_UNAVAILABLE = 503
STATUS_GATEWAY_TIMEOUT = 504